In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

In [2]:
from proj1_helpers import *
test=load_csv_data("../../dataset/test.csv", sub_sample=False)
train=load_csv_data("../../dataset/train.csv", sub_sample=False)

In [3]:
initial_w=np.array([0,0])
max_iters=50
gamma=1

In [4]:
train

(array([ 1., -1., -1., ...,  1., -1., -1.]),
 array([[ 138.47 ,   51.655,   97.827, ...,    1.24 ,   -2.475,  113.497],
        [ 160.937,   68.768,  103.235, ..., -999.   , -999.   ,   46.226],
        [-999.   ,  162.172,  125.953, ..., -999.   , -999.   ,   44.251],
        ..., 
        [ 105.457,   60.526,   75.839, ..., -999.   , -999.   ,   41.992],
        [  94.951,   19.362,   68.812, ..., -999.   , -999.   ,    0.   ],
        [-999.   ,   72.756,   70.831, ..., -999.   , -999.   ,    0.   ]]),
 array([100000, 100001, 100002, ..., 349997, 349998, 349999]))

In [ ]:
def least_squares_GD(y,tx,initial_w,max_iters,gamma):
    return w, loss

In [ ]:
def least_squares_SGD(y,tx,initial_w,max_iters,gamma):
    return w, loss

In [7]:
from costs import *
def least_squares(y,tx):
    if len(y)!=tx.shape[0]:
        raise ValueError("y and tx must have the same length")
    w = np.linalg.solve(np.dot(tx.transpose(), tx), np.dot(tx.transpose(), y))
    loss=compute_mse(y,tx,w)
    return w, loss

In [ ]:
def ridge_regression(y,tx,lambda_):
    return w, loss

In [ ]:
def logistic_regression(y,tx,initial_w,max_iters,gamma):
    return w, loss

In [ ]:
def reg_logistic_regression(y,tx,lambda_,initial_w,max_iters,gamma):
    return w, loss

In [8]:
w,loss=least_squares(train[0],train[1])

In [12]:
loss

0.3396868094770345

In [11]:
ypred=predict_labels(w,test[1])
create_csv_submission(test[2],ypred,"submission.csv")